# name: daily-scraper-and-report

# on:
#   schedule:
#     - cron: '54 16 * * *'  # Adjust cron as needed
#   workflow_dispatch:

# jobs:
#   scrape-and-email:
#     runs-on: ubuntu-latest
#     steps:
#       # Checkout repository
#       - name: Checkout repository
#         uses: actions/checkout@v4

#       # Set up Python
#       - name: Set up Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: 3.9

#       # Install dependencies
#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install webdriver-manager selenium beautifulsoup4 pandas

#       # Update CA certificates to fix SSL verification issues
#       - name: Update CA certificates
#         run: sudo apt-get install --reinstall -y ca-certificates

#       # Install Google Chrome
#       - name: Install Google Chrome
#         run: |
#           wget -q -O google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
#           sudo dpkg -i google-chrome.deb || sudo apt-get install -f -y

#       # Install ChromeDriver
#       - name: Install ChromeDriver
#         run: |
#           wget -q -O chromedriver.zip https://chromedriver.storage.googleapis.com/$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip
#           unzip chromedriver.zip -d /usr/local/bin/
#           chmod +x /usr/local/bin/chromedriver

#       - name: Verify Google Chrome Version
#         run: google-chrome --version

#       - name: Verify ChromeDriver Version
#         run: chromedriver --version

#       - name: Test ChromeDriver
#         run: |
#           echo "from selenium import webdriver
#           from selenium.webdriver.chrome.service import Service
#           from selenium.webdriver.chrome.options import Options
#           from webdriver_manager.chrome import ChromeDriverManager
#           options = Options()
#           options.add_argument('--headless')
#           options.add_argument('--no-sandbox')
#           options.binary_location = '/usr/bin/google-chrome'
#           driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)
#           driver.get('https://www.google.com')
#           print(driver.title)
#           driver.quit()" > test_chrome.py
#           python test_chrome.py
#       - name: Test website connectivity
#         run: curl -I https://www.ripplesnigeria.com/
#       - name: Debug environment variables
#         run: |
#           echo "User email: $USER_EMAIL"
#           echo "Password length: ${#USER_PASSWORD}"

#       # Run the scraper and email script
#       - name: Run scraper and email script
#         env:
#           USER_EMAIL: ${{ secrets.USER_EMAIL }}
#           USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
#         run: python scraper.py --debug


name: daily-scraper-and-report

on:
  schedule:
    - cron: '54 16 * * *'  # Adjust cron as needed
  workflow_dispatch:

jobs:
  scrape-and-email:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install webdriver-manager selenium beautifulsoup4 pandas

      # Update CA certificates to fix SSL verification issues
      - name: Update CA certificates
        run: sudo apt-get install --reinstall -y ca-certificates

      # Install Google Chrome
      - name: Install Google Chrome
        run: |
          wget -q -O google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome.deb || sudo apt-get install -f -y

      # Install ChromeDriver
      - name: Install ChromeDriver
        run: |
          wget -q -O chromedriver.zip https://chromedriver.storage.googleapis.com/$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip
          unzip chromedriver.zip -d /usr/local/bin/
          chmod +x /usr/local/bin/chromedriver

      # Verify Google Chrome Version
      - name: Verify Google Chrome Version
        run: google-chrome --version

      # Verify ChromeDriver Version
      - name: Verify ChromeDriver Version
        run: chromedriver --version

      # Test ChromeDriver functionality
      - name: Test ChromeDriver
        run: |
          echo "from selenium import webdriver
          from selenium.webdriver.chrome.service import Service
          from selenium.webdriver.chrome.options import Options
          from webdriver_manager.chrome import ChromeDriverManager
          options = Options()
          options.add_argument('--headless')
          options.add_argument('--no-sandbox')
          options.add_argument('--disable-dev-shm-usage')
          options.binary_location = '/usr/bin/google-chrome'
          driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)
          driver.get('https://www.google.com')
          print(driver.title)
          driver.quit()" > test_chrome.py
          python test_chrome.py

      # Test website connectivity
      - name: Test website connectivity
        run: curl -I https://www.ripplesnigeria.com/

      # Debug environment variables
      - name: Debug environment variables
        env:
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
        run: |
          echo "User email: $USER_EMAIL"
          echo "Password length: ${#USER_PASSWORD}"

      # Run the scraper and email script
      - name: Run scraper and email script
        env:
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
        run: python scraper.py --debug
